### ISSUE TITLE
Use npm to handle your dependencies

### ISSUE THREAD

**Issue by thomaspaillot** [Matis24/ConnectedData_Project#1]
Votre repo ne contient pas de fichier package.json, donc à priori le code que vous avez écrit qui fait par un require du package dotenv ne doit pas fonctionner. Utiliser `npm init`pour initialiser votre projet et `npm install [package]` pour installer vos dépendances.

**Comment by Matis24** [comment]
le package.json était dans mon .gitignore je l'ai enlevé.
