### ISSUE TITLE
Correctly name your functions

### ISSUE THREAD

**Issue by thomaspaillot** [Matis24/ConnectedData_Project#3]
https://github.com/Matis24/ConnectedData_Project/blob/c67084a9b74887130bd31254e021cae6f6eff2f1/code/PlantnetAPI.js#L1

Cette fonction pourrait plutôt s'appeler `getPlantNetSpecies` ou `fetchPlantNetSpecies`.

Une fonction qui s'appelerait plantNetAPI ferait plutôt ça :

```js
async function plantNetAPI(path, { apiKey, lang = en }) {
  const response = await fetch(`https://my-api.plantnet.org/v2/${path}?api-key=${apiKey}&lang=${lang}`);
  return response.json();
};
```

Et vous pourriez l'utiliser dans votre fonction `getPlantNetSpecies` de cette manière :

```js
function getPlantNetSpecies(apiKey) {
  return plantNetAPI('species', { apiKey });
};
```

De cette manière si vous avez besoin d'utiliser une autre route de l'API plantnet vous éviteriez de répéter du code : 

```js
function getPlantNetProjects(apiKey) {
  return plantNetAPI('projects', { apiKey });
};
```

**Comment by Matis24** [comment]
Les modifications ont étaient effectuées
